version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    environment:
      POSTGRES_DB: attendance_tracker_staging
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    volumes:
      - redis_staging_data:/data

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    container_name: attendance_backend_staging
    environment:
      NODE_ENV: staging
      DB_NAME: attendance_tracker_staging
    ports:
      - "3001:3000"

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    container_name: attendance_frontend_staging
    ports:
      - "8080:80"

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  default:
    name: attendance_staging_network
