      - name: Generate Production Environment Files
        run: |
          echo "🔧 Generating production environment files from templates..."
          ssh root@77.37.121.27 "
            cd '${{ env.DEPLOY_PATH }}' && 
            
            # Set environment variables for template processing
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            export JWT_SECRET='${{ secrets.JWT_SECRET }}'
            export REFRESH_TOKEN_SECRET='${{ secrets.REFRESH_TOKEN_SECRET }}'
            export JWT_REFRESH_SECRET='${{ secrets.JWT_REFRESH_SECRET }}'
            export SESSION_SECRET='${{ secrets.SESSION_SECRET }}'
            export EMAIL_HOST='${{ secrets.EMAIL_HOST }}'
            export EMAIL_PORT='${{ secrets.EMAIL_PORT }}'
            export EMAIL_SECURE='${{ secrets.EMAIL_SECURE }}'
            export EMAIL_USER='${{ secrets.EMAIL_USER }}'
            export EMAIL_PASS='${{ secrets.EMAIL_PASS }}'
            export EMAIL_FROM='${{ secrets.EMAIL_FROM }}'
            export COMPANY_NAME='${{ secrets.COMPANY_NAME }}'
            export COMPANY_ADDRESS='${{ secrets.COMPANY_ADDRESS }}'
            export SUPPORT_EMAIL='${{ secrets.SUPPORT_EMAIL }}'
            export YOUTUBE_CLIENT_ID='${{ secrets.YOUTUBE_CLIENT_ID }}'
            export YOUTUBE_CLIENT_SECRET='${{ secrets.YOUTUBE_CLIENT_SECRET }}'
            export YOUTUBE_API_KEY='${{ secrets.YOUTUBE_API_KEY }}'
            export CLOUDINARY_CLOUD_NAME='${{ secrets.CLOUDINARY_CLOUD_NAME }}'
            export CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}'
            export CLOUDINARY_API_SECRET='${{ secrets.CLOUDINARY_API_SECRET }}'
            export GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}'
            export GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}'
            export FACEBOOK_APP_ID='${{ secrets.FACEBOOK_APP_ID }}'
            export FACEBOOK_APP_SECRET='${{ secrets.FACEBOOK_APP_SECRET }}'
            export GITHUB_CLIENT_ID='${{ secrets.GITHUB_CLIENT_ID }}'
            export GITHUB_CLIENT_SECRET='${{ secrets.GITHUB_CLIENT_SECRET }}'
            export LINKEDIN_CLIENT_ID='${{ secrets.LINKEDIN_CLIENT_ID }}'
            export LINKEDIN_CLIENT_SECRET='${{ secrets.LINKEDIN_CLIENT_SECRET }}'
            export GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}'
            export SENTRY_DSN='${{ secrets.SENTRY_DSN }}'
            
            # Generate environment files using the script
            ./scripts/generate-env.sh
            
            echo '✅ Environment files generated successfully'
          "
